// frontend-svelte/src/routes/login/+page.svelte
<script lang="ts">
  import { login } from "$lib/auth";
  import { goto } from "$app/navigation";
  import {
    Loader2,
    Mail,
    Lock,
    ArrowRight,
    ShieldCheck,
    Zap,
  } from "lucide-svelte";
  import { Card, Button, Input } from "$lib";

  let email = "";
  let password = "";
  let isLoading = false;
  let error = "";

  async function handleSubmit() {
    if (!email || !password) {
      error = "Preencha todos os campos para continuar";
      return;
    }

    isLoading = true;
    error = "";

    try {
      await login(email, password);
      goto("/");
    } catch (err: any) {
      error = err.message || "Credenciais inválidas. Tente novamente.";
    } finally {
      isLoading = false;
    }
  }
</script>

<div
  class="min-h-screen bg-surface-50 flex items-center justify-center p-6 relative overflow-hidden"
>
  <!-- Background Decorations -->
  <div
    class="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-brand-500/5 rounded-full blur-[120px]"
  ></div>
  <div
    class="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-brand-600/5 rounded-full blur-[120px]"
  ></div>

  <div class="w-full max-w-md relative z-10">
    <!-- Logo & Branding -->
    <div
      class="text-center mb-10 animate-in fade-in slide-in-from-bottom-4 duration-700"
    >
      <div class="relative inline-block mb-6">
        <div
          class="w-24 h-24 bg-brand-600 rounded-[2.5rem] flex items-center justify-center shadow-2xl shadow-brand-600/30"
        >
          <ShieldCheck class="w-12 h-12 text-white" />
        </div>
        <div
          class="absolute -top-2 -right-2 w-10 h-10 bg-white rounded-2xl flex items-center justify-center shadow-lg"
        >
          <Zap class="w-6 h-6 text-yellow-500 fill-yellow-500" />
        </div>
      </div>
      <h1 class="text-4xl font-black text-surface-900 tracking-tight">
        Inovar Refrigeração
      </h1>
      <p class="text-surface-500 font-bold mt-3 text-lg">
        Sistema de Gestão Inteligente
      </p>
    </div>

    <!-- Login Card -->
    <Card
      padding="p-10"
      className="shadow-2xl shadow-surface-900/5 animate-in fade-in slide-in-from-bottom-8 duration-1000 delay-200"
    >
      {#if error}
        <div
          class="mb-8 p-4 rounded-2xl bg-red-50 border border-red-100 flex items-center gap-3 text-red-600 animate-in zoom-in duration-300"
        >
          <div class="p-2 bg-white rounded-lg shadow-sm">
            <Lock class="w-4 h-4" />
          </div>
          <p class="text-sm font-bold">{error}</p>
        </div>
      {/if}

      <form on:submit|preventDefault={handleSubmit} class="space-y-8">
        <div class="space-y-6">
          <Input
            label="E-mail Corporativo"
            type="email"
            bind:value={email}
            placeholder="nome@empresa.com"
            required
            disabled={isLoading}
          />

          <div class="space-y-2">
            <Input
              label="Senha de Acesso"
              type="password"
              bind:value={password}
              placeholder="••••••••"
              required
              disabled={isLoading}
            />
            <div class="flex justify-end">
              <button
                type="button"
                class="text-xs font-black text-brand-600 uppercase tracking-widest hover:text-brand-700 transition-colors"
              >
                Esqueceu a senha?
              </button>
            </div>
          </div>
        </div>

        <Button
          type="submit"
          variant="primary"
          fullWidth
          size="lg"
          loading={isLoading}
          className="shadow-xl shadow-brand-600/20 h-14 text-lg"
        >
          Entrar no Sistema
          {#if !isLoading}
            <ArrowRight class="w-5 h-5 ml-2" />
          {/if}
        </Button>
      </form>
    </Card>

    <!-- Footer -->
    <div class="mt-10 text-center animate-in fade-in duration-1000 delay-500">
      <p class="text-sm font-bold text-surface-400 uppercase tracking-widest">
        © 2026 Inovar Refrigeração
      </p>
      <div class="flex items-center justify-center gap-6 mt-4">
        <a
          href="/suporte"
          class="text-xs font-black text-surface-400 hover:text-brand-600 transition-colors uppercase tracking-widest"
          >Suporte</a
        >
        <span class="w-1 h-1 bg-surface-300 rounded-full"></span>
        <a
          href="#"
          class="text-xs font-black text-surface-400 hover:text-brand-600 transition-colors uppercase tracking-widest"
          >Privacidade</a
        >
      </div>
    </div>
  </div>
</div>

<style>
  :global(body) {
    background-color: var(--color-surface-50);
  }
</style>

// frontend/src/pages/Login.tsx
import React, { useState, useEffect } from 'react';
import { Button } from '../components/Botao';
import { Usuario } from '../types';
import { authService } from '../services/authService';
import { BotaoGooglePersonalizado } from '../components/BotaoGooglePersonalizado';
import { LogIn, Key, Mail, AlertTriangle, Loader2, Snowflake } from 'lucide-react';
import { API_BASE } from '../services/api';

interface LoginProps {
  onLogin: (user: Usuario) => void;
}

export const Login: React.FC<LoginProps> = ({ onLogin }) => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [backendReady, setBackendReady] = useState(false);

  // Warm-up: acordar backend Vercel enquanto usuário vê tela de login
  useEffect(() => {
    const warmupBackend = async () => {
      try {
        const response = await fetch(`${API_BASE}/api/health`, { method: 'GET' });
        if (response.ok) {
          setBackendReady(true);
        }
      } catch {
        // Backend pode estar acordando, tenta novamente em 3s
        setTimeout(warmupBackend, 3000);
      }
    };
    warmupBackend();
  }, []);

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setIsLoading(true);

    try {
      const data = await authService.login(email, password);
      const user = data.usuario;
      // Single-tenant: No company status checks needed
      onLogin(user);
    } catch (err: any) {
      console.error('Login Error:', err);
      let errorMsg = 'Erro ao conectar ao servidor.';

      if (err.response?.data) {
        const data = err.response.data;
        if (data.error) {
          errorMsg = typeof data.error === 'object' ? JSON.stringify(data.error) : String(data.error);
        } else if (data.message) {
          errorMsg = String(data.message);
        } else {
          errorMsg = typeof data === 'object' ? JSON.stringify(data) : String(data);
        }
      } else if (err.message) {
        errorMsg = err.message;
      }

      setError(errorMsg);
    } finally {
      setIsLoading(false);
    }
  };

  const handleGoogleSuccess = async (response: any) => {
    setError('');
    setIsLoading(true);

    try {
      const data = await authService.googleLogin(response.access_token);
      const user = data.usuario;
      // Single-tenant: No company status checks needed
      onLogin(user);
    } catch (err: any) {
      console.error('Google Login Error:', err);
      let errorMsg = 'Erro ao fazer login com Google.';

      if (err.response?.data) {
        const data = err.response.data;
        if (data.error) {
          errorMsg = typeof data.error === 'object' ? JSON.stringify(data.error) : String(data.error);
        } else if (data.message) {
          errorMsg = String(data.message);
        } else {
          errorMsg = typeof data === 'object' ? JSON.stringify(data) : String(data);
        }
      } else if (err.message) {
        errorMsg = err.message;
      }

      setError(errorMsg);
    } finally {
      setIsLoading(false);
    }
  };

  const handleGoogleError = () => {
    setError('Erro ao conectar com Google. Tente novamente.');
  };

  return (
    <div className="min-h-screen min-h-dvh flex flex-col bg-gradient-to-br from-brand-50 via-white to-surface-100">
      {/* Header decorativo */}
      <div className="absolute top-0 left-0 right-0 h-72 bg-gradient-to-b from-brand-500/10 to-transparent pointer-events-none" />

      {/* Conteúdo principal */}
      <div className="flex-1 flex flex-col items-center justify-center px-4 py-8 sm:px-6 lg:px-8 relative z-10">
        {/* Logo e título */}
        <div className="text-center mb-8 animate-in">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-brand-500 shadow-lg shadow-brand-500/30 mb-4">
            <Snowflake className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-3xl font-bold text-surface-800">
            Inovar Refrigeração
          </h1>
          <p className="mt-2 text-surface-500">
            Sistema de Gestão de Serviços
          </p>
        </div>

        {/* Card de login */}
        <div className="w-full max-w-sm animate-in" style={{ animationDelay: '0.1s' }}>
          <div className="card p-6 sm:p-8">
            {/* Login com Google */}
            <div className="mb-6">
              <BotaoGooglePersonalizado
                onSuccess={handleGoogleSuccess}
                onError={handleGoogleError}
                text="Entrar com Google"
              />
            </div>

            {/* Divisor */}
            <div className="relative mb-6">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-surface-200" />
              </div>
              <div className="relative flex justify-center">
                <span className="px-4 bg-white text-sm text-surface-400">
                  ou entre com email
                </span>
              </div>
            </div>

            {/* Formulário */}
            <form onSubmit={handleLogin} className="space-y-4">
              <div>
                <label htmlFor="email" className="block text-sm font-medium text-surface-700 mb-1.5">
                  Email
                </label>
                <div className="relative">
                  <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
                    <Mail className="h-5 w-5 text-surface-400" />
                  </div>
                  <input
                    id="email"
                    type="email"
                    required
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    disabled={isLoading}
                    className="input pl-11"
                    placeholder="seu@email.com"
                  />
                </div>
              </div>

              <div>
                <label htmlFor="password" className="block text-sm font-medium text-surface-700 mb-1.5">
                  Senha
                </label>
                <div className="relative">
                  <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
                    <Key className="h-5 w-5 text-surface-400" />
                  </div>
                  <input
                    id="password"
                    type="password"
                    required
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    disabled={isLoading}
                    className="input pl-11"
                    placeholder="••••••••"
                  />
                </div>
              </div>

              {/* Erro */}
              {error && (
                <div className="flex items-start gap-3 p-4 rounded-xl bg-red-50 border border-red-100 animate-in">
                  <AlertTriangle className="h-5 w-5 text-red-500 flex-shrink-0 mt-0.5" />
                  <p className="text-sm text-red-700">{error}</p>
                </div>
              )}

              {/* Botão de login */}
              <button
                type="submit"
                disabled={isLoading}
                className="btn btn-primary w-full"
              >
                {isLoading ? (
                  <Loader2 className="w-5 h-5 animate-spin" />
                ) : (
                  <LogIn className="w-5 h-5" />
                )}
                <span>{isLoading ? 'Entrando...' : 'Entrar'}</span>
              </button>
            </form>

            {/* Link para registro */}
            <div className="mt-6 pt-6 border-t border-surface-100">
              <p className="text-center text-sm text-surface-500 mb-4">
                Esqueceu sua senha?
              </p>
              <button
                type="button"
                onClick={() => alert('Entre em contato com o administrador.')}
                className="font-medium text-blue-600 hover:text-blue-500 transition-colors w-full text-center"
              >
                Recuperar acesso
              </button>
            </div>
          </div>
        </div>

        {/* Footer */}
        <p className="mt-8 text-center text-xs text-surface-400 animate-in" style={{ animationDelay: '0.2s' }}>
          © 2024 Inovar Refrigeração. Todos os direitos reservados.
        </p>
      </div>
    </div>
  );
};

export default Login;
