// frontend-svelte/src/routes/whatsapp/+page.svelte
<script lang="ts">
    import { onMount, onDestroy } from "svelte";
    import {
        QrCode,
        Wifi,
        WifiOff,
        Clock,
        ShieldCheck,
        Settings,
        Power,
        Loader2,
        Save,
        MessageSquare,
        Zap,
        Shield,
        AlertCircle,
        RefreshCw,
        Smartphone,
        CheckCircle2,
    } from "lucide-svelte";
    import { Card, Badge, Button, Input, Modal, Skeleton } from "$lib";

    interface BotStatus {
        connected: boolean;
        status: "conectado" | "desconectado" | "aguardando_qr";
        qr_code?: string;
    }

    interface BotConfig {
        ativo: boolean;
        min_delay: number;
        max_delay: number;
        hora_inicio: string;
        hora_fim: string;
    }

    let status: BotStatus | null = null;
    let config: BotConfig | null = null;
    let loading = true;
    let saving = false;
    let interval: ReturnType<typeof setInterval>;

    async function fetchStatus() {
        try {
            const token = localStorage.getItem("token");
            const res = await fetch("/api/whatsapp/status", {
                headers: { Authorization: `Bearer ${token}` },
            });
            if (res.ok) {
                status = await res.json();
            }
        } catch (error) {
            console.error("Erro ao buscar status:", error);
        } finally {
            loading = false;
        }
    }

    async function fetchConfig() {
        try {
            const token = localStorage.getItem("token");
            const res = await fetch("/api/whatsapp/config", {
                headers: { Authorization: `Bearer ${token}` },
            });
            if (res.ok) {
                config = await res.json();
            }
        } catch (error) {
            console.error("Erro ao buscar config:", error);
        }
    }

    async function saveConfig() {
        if (!config) return;
        saving = true;
        try {
            const token = localStorage.getItem("token");
            await fetch("/api/whatsapp/config", {
                method: "PUT",
                headers: {
                    Authorization: `Bearer ${token}`,
                    "Content-Type": "application/json",
                },
                body: JSON.stringify(config),
            });
            alert("Configurações salvas com sucesso!");
        } catch (error) {
            console.error("Erro ao salvar:", error);
        } finally {
            saving = false;
        }
    }

    async function reconnect() {
        try {
            const token = localStorage.getItem("token");
            await fetch("/api/whatsapp/reconnect", {
                method: "POST",
                headers: { Authorization: `Bearer ${token}` },
            });
            await fetchStatus();
        } catch (error) {
            console.error("Erro ao reconectar:", error);
        }
    }

    onMount(() => {
        fetchStatus();
        fetchConfig();
        interval = setInterval(fetchStatus, 5000);
    });

    onDestroy(() => {
        if (interval) clearInterval(interval);
    });
</script>

<div class="min-h-screen bg-surface-50 pb-24">
    <!-- Header -->
    <div class="bg-white border-b border-surface-200 px-4 py-8">
        <div
            class="max-w-7xl mx-auto flex flex-col md:flex-row md:items-center justify-between gap-6"
        >
            <div>
                <h1
                    class="text-4xl font-black text-surface-900 tracking-tight flex items-center gap-3"
                >
                    <MessageSquare class="w-10 h-10 text-green-600" />
                    WhatsApp Brain
                </h1>
                <p class="text-surface-500 font-bold mt-2">
                    Motor de automação inteligente e gestão de conexão segura
                </p>
            </div>
            <div class="flex items-center gap-3">
                {#if status?.connected}
                    <Badge
                        variant="success"
                        size="lg"
                        className="px-6 py-3 text-sm"
                    >
                        <Wifi class="w-4 h-4 mr-2" /> ONLINE
                    </Badge>
                {:else if status?.status === "aguardando_qr"}
                    <Badge
                        variant="warning"
                        size="lg"
                        className="px-6 py-3 text-sm"
                    >
                        <QrCode class="w-4 h-4 mr-2" /> AGUARDANDO QR
                    </Badge>
                {:else}
                    <Badge
                        variant="danger"
                        size="lg"
                        className="px-6 py-3 text-sm"
                    >
                        <WifiOff class="w-4 h-4 mr-2" /> DESCONECTADO
                    </Badge>
                {/if}
            </div>
        </div>
    </div>

    <div class="max-w-7xl mx-auto px-4 py-8">
        {#if loading}
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
                <Skeleton className="h-[400px] rounded-[3rem]" />
                <Skeleton className="h-[400px] rounded-[3rem]" />
            </div>
        {:else}
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
                <!-- Connection Status Card -->
                <Card padding="p-8" className="relative overflow-hidden">
                    <div class="flex items-center gap-4 mb-10">
                        <div class="p-3 bg-green-50 rounded-2xl text-green-600">
                            <Smartphone class="w-6 h-6" />
                        </div>
                        <div>
                            <h2
                                class="text-2xl font-black text-surface-900 tracking-tight"
                            >
                                Conexão
                            </h2>
                            <p class="text-surface-500 font-bold">
                                Status do pareamento com seu dispositivo
                            </p>
                        </div>
                    </div>

                    <div
                        class="flex flex-col items-center justify-center min-h-[300px] py-8"
                    >
                        {#if status?.status === "conectado"}
                            <div
                                class="text-center space-y-6 animate-in zoom-in duration-500"
                            >
                                <div class="relative">
                                    <div
                                        class="w-32 h-32 bg-green-100 rounded-[2.5rem] flex items-center justify-center mx-auto shadow-xl shadow-green-500/20"
                                    >
                                        <ShieldCheck
                                            class="w-16 h-16 text-green-600"
                                        />
                                    </div>
                                    <div
                                        class="absolute -top-2 -right-2 w-8 h-8 bg-white rounded-full flex items-center justify-center shadow-lg"
                                    >
                                        <Zap
                                            class="w-5 h-5 text-yellow-500 fill-yellow-500"
                                        />
                                    </div>
                                </div>
                                <div>
                                    <h3
                                        class="text-3xl font-black text-surface-900 tracking-tight"
                                    >
                                        Conectado e Seguro
                                    </h3>
                                    <p
                                        class="text-surface-500 font-bold mt-2 max-w-xs mx-auto"
                                    >
                                        Seu bot está operando normalmente com
                                        proteção Anti-Ban ativa.
                                    </p>
                                </div>
                                <Button
                                    variant="ghost"
                                    className="text-red-500 hover:bg-red-50"
                                >
                                    <Power class="w-4 h-4 mr-2" /> Desconectar Instância
                                </Button>
                            </div>
                        {:else if status?.status === "aguardando_qr" && status?.qr_code}
                            <div
                                class="text-center space-y-8 animate-in fade-in duration-500"
                            >
                                <div class="space-y-2">
                                    <h3
                                        class="text-2xl font-black text-surface-900"
                                    >
                                        Escaneie o QR Code
                                    </h3>
                                    <p class="text-surface-500 font-bold">
                                        Abra o WhatsApp > Aparelhos Conectados
                                    </p>
                                </div>

                                <div
                                    class="relative inline-block p-6 bg-white rounded-[3rem] shadow-2xl border border-surface-100"
                                >
                                    <img
                                        src="data:image/png;base64,{status.qr_code}"
                                        alt="WhatsApp QR Code"
                                        class="w-64 h-64 object-contain"
                                    />
                                    <div
                                        class="absolute inset-0 border-4 border-brand-500 rounded-[3rem] animate-pulse pointer-events-none"
                                    ></div>
                                </div>

                                <div
                                    class="flex items-center justify-center gap-3 text-brand-600 font-black uppercase tracking-widest text-xs"
                                >
                                    <RefreshCw class="w-4 h-4 animate-spin" />
                                    Aguardando leitura...
                                </div>
                            </div>
                        {:else}
                            <div class="text-center space-y-6">
                                <div
                                    class="w-32 h-32 bg-surface-100 rounded-[2.5rem] flex items-center justify-center mx-auto"
                                >
                                    <WifiOff
                                        class="w-16 h-16 text-surface-300"
                                    />
                                </div>
                                <div>
                                    <h3
                                        class="text-2xl font-black text-surface-900"
                                    >
                                        Sem Conexão Ativa
                                    </h3>
                                    <p
                                        class="text-surface-500 font-bold mt-2 max-w-xs mx-auto"
                                    >
                                        Inicie uma nova conexão para começar a
                                        enviar notificações automáticas.
                                    </p>
                                </div>
                                <Button
                                    variant="primary"
                                    size="lg"
                                    on:click={reconnect}
                                    className="px-12 shadow-xl shadow-brand-500/20"
                                >
                                    Iniciar Nova Conexão
                                </Button>
                            </div>
                        {/if}
                    </div>
                </Card>

                <!-- Anti-Ban Configuration Card -->
                <Card padding="p-8">
                    <div class="flex items-center gap-4 mb-10">
                        <div class="p-3 bg-brand-50 rounded-2xl text-brand-600">
                            <Shield class="w-6 h-6" />
                        </div>
                        <div>
                            <h2
                                class="text-2xl font-black text-surface-900 tracking-tight"
                            >
                                Configurações Anti-Ban
                            </h2>
                            <p class="text-surface-500 font-bold">
                                Parâmetros de segurança para evitar bloqueios
                            </p>
                        </div>
                    </div>

                    {#if config}
                        <form
                            on:submit|preventDefault={saveConfig}
                            class="space-y-8"
                        >
                            <!-- Status Toggle -->
                            <div
                                class="p-6 bg-surface-50 rounded-[2rem] border border-surface-100 flex items-center justify-between group hover:bg-white hover:shadow-xl transition-all duration-300"
                            >
                                <div class="flex items-center gap-4">
                                    <div
                                        class="w-12 h-12 bg-white rounded-xl shadow-sm flex items-center justify-center {config.ativo
                                            ? 'text-green-600'
                                            : 'text-surface-400'}"
                                    >
                                        <Zap
                                            class="w-6 h-6 {config.ativo
                                                ? 'fill-green-500'
                                                : ''}"
                                        />
                                    </div>
                                    <div>
                                        <p class="font-black text-surface-900">
                                            Bot de Automação
                                        </p>
                                        <p
                                            class="text-xs font-bold text-surface-500"
                                        >
                                            Ativa ou pausa todos os envios
                                        </p>
                                    </div>
                                </div>
                                <button
                                    type="button"
                                    on:click={() =>
                                        (config.ativo = !config.ativo)}
                                    class="relative inline-flex h-8 w-14 items-center rounded-full transition-colors focus:outline-none {config.ativo
                                        ? 'bg-green-500'
                                        : 'bg-surface-300'}"
                                >
                                    <span
                                        class="inline-block h-6 w-6 transform rounded-full bg-white transition-transform {config.ativo
                                            ? 'translate-x-7'
                                            : 'translate-x-1'}"
                                    ></span>
                                </button>
                            </div>

                            <!-- Delay Settings -->
                            <div class="space-y-4">
                                <h3
                                    class="text-xs font-black text-surface-400 uppercase tracking-widest flex items-center gap-2 ml-1"
                                >
                                    <Clock class="w-3 h-3" /> Intervalos entre Mensagens
                                </h3>
                                <div class="grid grid-cols-2 gap-6">
                                    <Input
                                        label="Mínimo (segundos)"
                                        type="number"
                                        bind:value={config.min_delay}
                                    />
                                    <Input
                                        label="Máximo (segundos)"
                                        type="number"
                                        bind:value={config.max_delay}
                                    />
                                </div>
                                <p
                                    class="text-[10px] font-bold text-surface-400 italic ml-1"
                                >
                                    * O sistema escolherá um tempo aleatório
                                    entre esses valores para simular
                                    comportamento humano.
                                </p>
                            </div>

                            <!-- Operating Hours -->
                            <div class="space-y-4">
                                <h3
                                    class="text-xs font-black text-surface-400 uppercase tracking-widest flex items-center gap-2 ml-1"
                                >
                                    <Calendar class="w-3 h-3" /> Horário de Funcionamento
                                </h3>
                                <div class="grid grid-cols-2 gap-6">
                                    <Input
                                        label="Início"
                                        type="time"
                                        bind:value={config.hora_inicio}
                                    />
                                    <Input
                                        label="Fim"
                                        type="time"
                                        bind:value={config.hora_fim}
                                    />
                                </div>
                            </div>

                            <div class="pt-4">
                                <Button
                                    type="submit"
                                    variant="primary"
                                    fullWidth
                                    size="lg"
                                    loading={saving}
                                    className="shadow-xl shadow-brand-500/20"
                                >
                                    <Save class="w-5 h-5 mr-2" /> Salvar Configurações
                                </Button>
                            </div>
                        </form>
                    {:else}
                        <div class="space-y-6">
                            <Skeleton className="h-20 rounded-2xl" />
                            <Skeleton className="h-40 rounded-2xl" />
                            <Skeleton className="h-40 rounded-2xl" />
                        </div>
                    {/if}
                </Card>
            </div>

            <!-- Tips Card -->
            <Card
                padding="p-8"
                className="lg:col-span-2 bg-brand-600 text-white border-none shadow-2xl shadow-brand-600/30"
            >
                <div class="flex flex-col md:flex-row items-center gap-8">
                    <div
                        class="w-20 h-20 bg-white/20 rounded-[2rem] flex items-center justify-center flex-shrink-0"
                    >
                        <CheckCircle2 class="w-10 h-10 text-white" />
                    </div>
                    <div class="flex-1 text-center md:text-left">
                        <h3 class="text-2xl font-black tracking-tight mb-2">
                            Dicas para evitar banimentos
                        </h3>
                        <p class="font-bold text-brand-100 opacity-90">
                            Evite enviar muitas mensagens para números que não
                            possuem seu contato salvo. Mantenha os intervalos de
                            delay acima de 15 segundos para maior segurança.
                        </p>
                    </div>
                    <Button
                        variant="ghost"
                        className="bg-white/10 hover:bg-white/20 text-white border-none px-8"
                    >
                        Saiba Mais
                    </Button>
                </div>
            </Card>
        {/if}
    </div>
</div>

// frontend/src/pages/WhatsApp.tsx

import React, { useState, useEffect } from 'react';
import { whatsappBrain, BotStatus, BotConfig } from '../services/whatsappBrain';
import { Button } from '../components/Botao';
import { QrCode, Wifi, WifiOff, Clock, ShieldCheck, Settings, Power } from 'lucide-react';
import { useNotification } from '../contexts/ContextoNotificacao';

export const WhatsApp: React.FC = () => {
    const { notify } = useNotification();
    const [status, setStatus] = useState<BotStatus | null>(null);
    const [config, setConfig] = useState<BotConfig | null>(null);
    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);

    // Polling Status every 5 seconds
    useEffect(() => {
        fetchStatus();
        fetchConfig();

        const interval = setInterval(fetchStatus, 5000);
        return () => clearInterval(interval);
    }, []);

    const fetchStatus = async () => {
        try {
            const data = await whatsappBrain.getStatus();
            setStatus(data);
        } catch (error) {
            console.error("Error fetching status", error);
        } finally {
            setLoading(false);
        }
    };

    const fetchConfig = async () => {
        try {
            const data = await whatsappBrain.getConfig();
            setConfig(data);
        } catch (error) {
            console.error("Error fetching config", error);
        }
    };

    const handleConfigSave = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!config) return;

        setSaving(true);
        try {
            await whatsappBrain.updateConfig(config);
            notify('Configurações salvas com sucesso!', 'success');
        } catch (error) {
            notify('Erro ao salvar configurações.', 'error');
        } finally {
            setSaving(false);
        }
    };

    const handleReconnect = async () => {
        try {
            await whatsappBrain.reconnect();
            notify('Tentativa de reconexão iniciada...', 'info');
            fetchStatus();
        } catch (error) {
            notify('Erro ao solicitar reconexão.', 'error');
        }
    };

    if (loading) {
        return (
            <div className="flex justify-center items-center h-64">
                <div className="w-8 h-8 border-4 border-brand-200 border-t-brand-600 rounded-full animate-spin"></div>
            </div>
        );
    }

    return (
        <div className="space-y-6">
            {/* Header */}
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-gray-800 flex items-center gap-2">
                        <ShieldCheck className="w-8 h-8 text-green-600" />
                        WhatsApp Brain (Neonize)
                    </h1>
                    <p className="text-gray-500">Motor Anti-Ban e Gestão de Conexão Segura</p>
                </div>

                <div className="flex items-center gap-3 bg-white p-2 rounded-lg shadow-sm border">
                    {status?.connected ? (
                        <div className="flex items-center gap-2 text-green-600 font-bold px-3 py-1 bg-green-50 rounded-full">
                            <Wifi className="w-5 h-5" />
                            <span>ONLINE</span>
                        </div>
                    ) : status?.status === 'aguardando_qr' ? (
                        <div className="flex items-center gap-2 text-orange-600 font-bold px-3 py-1 bg-orange-50 rounded-full">
                            <QrCode className="w-5 h-5" />
                            <span>Escaneie o QR</span>
                        </div>
                    ) : (
                        <div className="flex items-center gap-2 text-red-600 font-bold px-3 py-1 bg-red-50 rounded-full">
                            <WifiOff className="w-5 h-5" />
                            <span>Desconectado</span>
                        </div>
                    )}
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

                {/* 1. Connection Card */}
                <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
                    <div className="bg-gray-50 px-6 py-4 border-b border-gray-100 flex justify-between items-center">
                        <h2 className="font-semibold text-gray-700 flex items-center gap-2">
                            <QrCode className="w-5 h-5 text-gray-500" />
                            Conexão
                        </h2>
                    </div>
                    <div className="p-8 flex flex-col items-center justify-center min-h-[300px]">

                        {status?.status === 'conectado' ? (
                            <div className="text-center space-y-4">
                                <div className="w-24 h-24 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                                    <ShieldCheck className="w-12 h-12 text-green-600" />
                                </div>
                                <h3 className="text-xl font-bold text-gray-800">Conexão Segura Ativa</h3>
                                <p className="text-gray-500 max-w-xs mx-auto">
                                    Seu bot está rodando e protegido pelo sistema Anti-Ban.
                                </p>
                                <Button variant="outline" className="mt-4 text-red-600 hover:bg-red-50 border-red-200">
                                    <Power className="w-4 h-4 mr-2" />
                                    Desconectar
                                </Button>
                            </div>
                        ) : status?.status === 'aguardando_qr' && status?.qr_code ? (
                            <div className="text-center space-y-4">
                                <h3 className="font-bold text-gray-800 mb-2">Escaneie para Conectar</h3>
                                <div className="bg-white p-2 border rounded-lg shadow-sm inline-block">
                                    <img
                                        src={`data:image/png;base64,${status.qr_code}`}
                                        alt="WhatsApp QR Code"
                                        className="w-64 h-64 object-contain"
                                    />
                                </div>
                                <p className="text-sm text-gray-500 animate-pulse">
                                    Aguardando leitura do código...
                                </p>
                            </div>
                        ) : (
                            <div className="text-center space-y-4">
                                <div className="w-24 h-24 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
                                    <WifiOff className="w-10 h-10 text-gray-400" />
                                </div>
                                <h3 className="text-lg font-medium text-gray-600">Bot Desconectado</h3>
                                <p className="text-gray-500 text-sm max-w-xs mx-auto mb-4">
                                    Clique abaixo para iniciar o processo de conexão e gerar um novo QR Code.
                                </p>
                                <Button onClick={handleReconnect} className="bg-brand-600 hover:bg-brand-700 text-white">
                                    Iniciar Conexão
                                </Button>
                            </div>
                        )}
                    </div>
                </div>

                {/* 2. Configuration Card */}
                <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
                    <div className="bg-gray-50 px-6 py-4 border-b border-gray-100">
                        <h2 className="font-semibold text-gray-700 flex items-center gap-2">
                            <Settings className="w-5 h-5 text-gray-500" />
                            Configurações Anti-Ban
                        </h2>
                    </div>
                    <div className="p-6">
                        {config ? (
                            <form onSubmit={handleConfigSave} className="space-y-6">

                                {/* Status Switch */}
                                <div className="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
                                    <div>
                                        <label className="font-medium text-gray-700">Bot Ativo</label>
                                        <p className="text-xs text-gray-500">Pausa totalmente o envio de mensagens</p>
                                    </div>
                                    <div className="relative inline-block w-12 h-6 transition duration-200 ease-in-out">
                                        <input
                                            type="checkbox"
                                            checked={config.ativo}
                                            onChange={(e) => setConfig({...config, ativo: e.target.checked})}
                                            className="opacity-0 w-0 h-0"
                                            id="toggle-active"
                                        />
                                        <label htmlFor="toggle-active" className={`absolute cursor-pointer top-0 left-0 right-0 bottom-0 rounded-full transition-colors ${config.ativo ? 'bg-green-500' : 'bg-gray-300'}`}>
                                            <span className={`absolute left-1 top-1 bg-white w-4 h-4 rounded-full transition-transform ${config.ativo ? 'transform translate-x-6' : ''}`} />
                                        </label>
                                    </div>
                                </div>

                                {/* Delays */}
                                <div className="space-y-3">
                                    <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider flex items-center gap-2">
                                        <Clock className="w-4 h-4" />
                                        Delays (Aleatórios)
                                    </h3>
                                    <div className="grid grid-cols-2 gap-4">
                                        <div>
                                            <label className="block text-sm font-medium text-gray-700 mb-1">Mínimo (seg)</label>
                                            <input
                                                type="number"
                                                className="w-full border-gray-300 rounded-md shadow-sm focus:ring-brand-500 focus:border-brand-500"
                                                value={config.min_delay}
                                                onChange={(e) => setConfig({...config, min_delay: parseInt(e.target.value)})}
                                            />
                                        </div>
                                        <div>
                                            <label className="block text-sm font-medium text-gray-700 mb-1">Máximo (seg)</label>
                                            <input
                                                type="number"
                                                className="w-full border-gray-300 rounded-md shadow-sm focus:ring-brand-500 focus:border-brand-500"
                                                value={config.max_delay}
                                                onChange={(e) => setConfig({...config, max_delay: parseInt(e.target.value)})}
                                            />
                                        </div>
                                    </div>
                                </div>

                                {/* Sleep Hours */}
                                <div className="space-y-3">
                                    <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider flex items-center gap-2">
                                        <WifiOff className="w-4 h-4" />
                                        Modo Sono (Repouso)
                                    </h3>
                                    <div className="grid grid-cols-2 gap-4">
                                        <div>
                                            <label className="block text-sm font-medium text-gray-700 mb-1">Início</label>
                                            <input
                                                type="time"
                                                className="w-full border-gray-300 rounded-md shadow-sm focus:ring-brand-500 focus:border-brand-500"
                                                value={config.hora_inicio} // Note: This logic might need inversion depending on semantics "Start Working" vs "Start Sleeping". User schema says 'hora_inicio'/'hora_fim'. Assumption: Working Hours.
                                                // Actually lets check standard: 'hora_inicio' usually means start of active period.
                                                // My brain logic used 'sleep_start'.
                                                // User Schema: hora_inicio = 08:00 (Start Active), hora_fim = 21:00 (End Active).
                                                onChange={(e) => setConfig({...config, hora_inicio: e.target.value})}
                                            />
                                            <p className="text-xs text-gray-400 mt-1">Horário que começa a trabalhar</p>
                                        </div>
                                        <div>
                                            <label className="block text-sm font-medium text-gray-700 mb-1">Fim</label>
                                            <input
                                                type="time"
                                                className="w-full border-gray-300 rounded-md shadow-sm focus:ring-brand-500 focus:border-brand-500"
                                                value={config.hora_fim}
                                                onChange={(e) => setConfig({...config, hora_fim: e.target.value})}
                                            />
                                            <p className="text-xs text-gray-400 mt-1">Horário que vai dormir</p>
                                        </div>
                                    </div>
                                </div>

                                <Button type="submit" className="w-full bg-brand-600 hover:bg-brand-700 text-white" disabled={saving}>
                                    {saving ? 'Salvando...' : 'Salvar Alterações'}
                                </Button>
                            </form>
                        ) : (
                            <div className="text-center py-10 text-gray-400">
                                Carregando configurações...
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default WhatsApp;
